export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const GET_ALL_ADMINS_REQUEST = "GET_ALL_ADMINS_REQUEST";
export const GET_ALL_ADMINS_SUCCESS = "GET_ALL_ADMINS_SUCCESS";
export const GET_ALL_ADMINS_FAIL = "GET_ALL_ADMINS_FAIL";
export const GET_ALL_VENDORS_REQUEST = "GET_ALL_VENDORS_REQUEST";
export const GET_ALL_VENDORS_SUCCESS = "GET_ALL_VENDORS_SUCCESS";
export const GET_ALL_VENDORS_FAIL = "GET_ALL_VENDORS_FAIL";
export const UPDATE_USER_ROLE_REQUEST = "UPDATE_ROLE_REQUEST";
export const UPDATE_USER_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_USER_ROLE_FAIL = "UPDATE_ROLE_FAIL";
